baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Photo Gallery"
theme = "github.com/nicokaiser/hugo-theme-gallery/v4"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"